export interface Assistido {
  id: string;
  nome_completo: string;
  nome?: string;
  rg?: string | null;
  cpf?: string | null;
  data_nascimento?: string | null;
  idade?: number | string | null;
  raca_cor?: string | null;
  telefone?: string | null;
  endereco?: string | null;
  bairro?: string | null;
  escolaridade?: string | null;
  estado_civil?: string | null;
  possui_cadastro_flh?: boolean | null;
  possui_cras?: boolean | null;
  bairro_cras?: string | null;
  composicao_familiar?: number | string | null;
  quantidade_filhos?: number | string | null;
  atividade_remunerada?: string | null;
  profissao?: string | null;
  acesso_internet?: string | null;
  renda_familiar_aproximada?: number | null;
  renda_familiar_faixa?: string | null;
  beneficios_sociais?: string[] | null;
  tipo_moradia?: string | null;
  em_situacao_rua?: boolean | null;
  servicos_basicos_regulares?: boolean | null;
  dificuldades_enfrentadas?: string[] | null;
  rede_apoio?: string | null;
  fatores_risco_evasao?: string[] | null;
  possui_deficiencia?: boolean | null;
  tipos_deficiencia?: string[] | null;
  doencas_cronicas_familia?: string[] | string | null;
  servicos_acompanhamento?: string[] | null;
  motivo_busca?: string | null;
  expectativa_curso?: string | null;
  objetivo_profissional_3_meses?: string | null;
  curso_pretendido?: string | null;
  cursos_anteriores?: string[] | string | null;
  status_curso?: string | null;
  status_acompanhamento?: string | null;
  data_ingresso?: string | null;
  foto_url?: string | null;
  created_at?: string | null;
  criado_por?: string | null;
  atualizado_por?: string | null;
  updated_at?: string | null;
}
